/**
 * @fileoverview TypeScript type definitions for the Real Estate Stager Agent.
 *
 * Covers all external API shapes (Seedance, Butterbase Storage) and the
 * internal `staging_jobs` PostgreSQL row shape. All external response
 * fields use optional markers for defensive typing.
 */

// ── Seedance 2.0 (Volcengine Ark API) ───────────────────────

/**
 * Request body for creating a Seedance video generation task.
 * POST to `https://ark.cn-beijing.volces.com/api/v3/contents/generations/tasks`
 */
export interface SeedanceTaskCreateRequest {
  /** Model ID — e.g., 'doubao-seedance-2-0-260128' or 'doubao-seedance-2-0-fast-260128' */
  model: string;
  /** Array of content parts: one image_url and one text prompt */
  content: SeedanceContentPart[];
}

/** A single content part in a Seedance task request. */
export type SeedanceContentPart =
  | { type: 'image_url'; image_url: { url: string } }
  | { type: 'text'; text: string };

/**
 * Response from Seedance task creation and polling endpoints.
 *
 * - Create: `POST /contents/generations/tasks` returns `{ id, status }`
 * - Poll:   `GET  /contents/generations/tasks/{id}` returns all fields
 */
export interface SeedanceTaskResponse {
  /** Unique task identifier for polling */
  id: string;
  /** Current task status — poll until 'succeeded' or 'failed' */
  status: 'submitted' | 'running' | 'succeeded' | 'failed';
  /** URL to download the generated video (only present when status is 'succeeded') */
  video_url?: string;
  /** Error details (only present when status is 'failed') */
  error?: {
    code: string;
    message: string;
  };
}

// ── Butterbase Database ─────────────────────────────────────

/**
 * Row shape for the `staging_jobs` table in Butterbase PostgreSQL.
 *
 * Tracks the full lifecycle of a staging request:
 * processing → succeeded | failed
 */
export interface StagingJob {
  /** UUID primary key, auto-generated by PostgreSQL */
  id: string;
  /** Sender identifier from Photon Spectrum (message.sender.id) */
  sender_id: string;
  /** Butterbase storage objectId for the uploaded room image */
  image_object_id: string | null;
  /** Butterbase storage objectId for the generated staging video */
  video_object_id: string | null;
  /** Seedance task ID for tracking the video generation */
  seedance_task_id: string | null;
  /** Current job status */
  status: 'processing' | 'succeeded' | 'failed';
  /** Error message if status is 'failed' */
  error_message: string | null;
  /** ISO 8601 timestamp of job creation */
  created_at: string;
  /** ISO 8601 timestamp of last update */
  updated_at: string;
}

// ── Butterbase Storage API ──────────────────────────────────

/**
 * Response from Butterbase Storage upload authorization endpoint.
 * `POST /storage/{app_id}/upload`
 *
 * Returns a presigned URL to PUT the file bytes to, plus an objectId
 * to store as the permanent reference.
 */
export interface ButterbaseUploadResponse {
  /** Presigned URL to PUT the file bytes to (expires in 5 minutes) */
  uploadUrl: string;
  /** Storage path (e.g., 'app_id/user_id/uuid_filename.jpg') — do NOT use as a URL */
  objectKey: string;
  /** Unique object identifier — store this as the source of truth */
  objectId: string;
  /** Seconds until the upload URL expires (typically 300) */
  expiresIn: number;
}

/**
 * Response from Butterbase Storage download endpoint.
 * `GET /storage/{app_id}/download/{object_id}`
 *
 * Returns a presigned download URL that expires after 1 hour.
 */
export interface ButterbaseDownloadResponse {
  /** Presigned download URL (expires in 1 hour — never cache this) */
  downloadUrl: string;
  /** Original filename */
  filename: string;
  /** Seconds until the download URL expires (typically 3600) */
  expiresIn: number;
}

// ── Prompt Builder ──────────────────────────────────────────

/**
 * Options for customizing the staging prompt.
 *
 * Both fields are optional — omitting them produces a
 * high-quality general-purpose staging prompt.
 */
export interface StagingPromptOptions {
  /** Interior design style preset */
  style?: 'modern' | 'mid-century' | 'minimalist' | 'scandinavian' | 'luxury';
  /** Room type hint for more targeted furniture/decor suggestions */
  roomType?: 'living-room' | 'bedroom' | 'kitchen' | 'bathroom' | 'office';
}
